/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.app.parque.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 * GUIInicio: es la ventana principal (da la opcion al usuario de registrarse o
 * acceder).
 *
 * @author noelp
 */
public class GUIInicio extends javax.swing.JFrame {

    /**
     * tamPantalla: el tamanio de la pantalla.
     */
    private Dimension tamPantalla = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * panelIcon: el panel donde se situa el icono de la empresa.
     */
    private JPanel panelIcon;
    /**
     * panelOpciones: el panel donde se encuentran los botones de opciones.
     */
    private JPanel panelOpciones;

    /**
     * optText: el texto de los botones.
     */
    public static final String[] optText = {"Entrar", "Registrarse"};

    /**
     * optButtons: una lista que contiene los botones.
     */
    private List<JButton> optButtons = new ArrayList<>();

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
        setFrame();
    }

    /**
     * setFrame: es el metodo principal que coloca los elementos en la ventana.
     */
    private void setFrame() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setSize(tamPantalla);
        this.setTitle("DRAGONVALL");
        this.getContentPane().setLayout(new BorderLayout());
        setImage();
        setOptPanel();
    }

    /**
     * setImage: coloca el icono en la ventana.
     */
    private void setImage() {
        panelIcon = new JPanel(new BorderLayout());
        this.getContentPane().add(panelIcon);
        JLabel image = new JLabel(new ImageIcon(".\\src\\main\\java\\com\\gf\\app\\parque\\resources\\Dragonvall-Logo.png"));
        panelIcon.add(image, BorderLayout.CENTER);
        image.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * setOptPanel: coloca los botones en la pantalla.
     */
    private void setOptPanel() {
        panelOpciones = new JPanel(new GridLayout(1, 2, 5, 0));
        panelOpciones.setPreferredSize(new Dimension((int) tamPantalla.getWidth(), (int) (tamPantalla.getHeight() * 0.2)));
        this.getContentPane().add(panelOpciones, BorderLayout.SOUTH);
        for (int i = 0; i < 2; i++) {
            JButton opt = new JButton(optText[i]);
            optButtons.add(opt);
            panelOpciones.add(opt);
        }
    }

    /**
     * getOptButtons: devuelve una lista de botones. Son las opciones de acceso.
     *
     * @return una lista de botones
     */
    public List<JButton> getOptButtons() {
        return optButtons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
