/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.app.parque.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author noelp
 */
public class GUIInicio extends javax.swing.JFrame {

    private Dimension tamPantalla = Toolkit.getDefaultToolkit().getScreenSize();

    private JPanel panelIcon;
    private JPanel panelOpciones;

    public static final String[] optText = {"Entrar", "Registrarse"};

    private List<JButton> optButtons = new ArrayList<>();

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setSize(tamPantalla);
        this.setTitle("DRAGONVALL");
        this.getContentPane().setLayout(new BorderLayout());
        setImage();
        setOptPanel();
    }

    private void setImage() {
        panelIcon = new JPanel(new BorderLayout());
        this.getContentPane().add(panelIcon);
        JLabel image = new JLabel(new ImageIcon(".\\src\\main\\java\\com\\gf\\app\\parque\\resources\\Dragonvall-Logo.png"));
        panelIcon.add(image, BorderLayout.CENTER);
        image.setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void setOptPanel() {
        panelOpciones = new JPanel(new GridLayout(1, 2, 5, 0));
        panelOpciones.setPreferredSize(new Dimension((int) tamPantalla.getWidth(), (int) (tamPantalla.getHeight() * 0.2)));
        this.getContentPane().add(panelOpciones, BorderLayout.SOUTH);
        for (int i = 0; i < 2; i++) {
            JButton opt = new JButton(optText[i]);
            optButtons.add(opt);
            panelOpciones.add(opt);
        }
    }

    public List<JButton> getOptButtons() {
        return optButtons;
    }

    public void setOptButtons(List<JButton> optButtons) {
        this.optButtons = optButtons;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIInicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
